// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"mini-titok/service/relation/rpc/internal/logic"
	"mini-titok/service/relation/rpc/internal/svc"
	"mini-titok/service/relation/rpc/relationclient"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relationclient.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) Action(ctx context.Context, in *relationclient.ActionRequest) (*relationclient.ActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *RelationServer) FollowList(ctx context.Context, in *relationclient.FollowListRequest) (*relationclient.FollowListResponse, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *RelationServer) FansList(ctx context.Context, in *relationclient.FansListRequest) (*relationclient.FansListResponse, error) {
	l := logic.NewFansListLogic(ctx, s.svcCtx)
	return l.FansList(in)
}
