// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"mini-titok/service/relation/rpc/internal/logic"
	"mini-titok/service/relation/rpc/internal/svc"
	"mini-titok/service/relation/rpc/relationclient"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relationclient.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) FollowAction(ctx context.Context, in *relationclient.FollowActionRequest) (*relationclient.FollowActionResponse, error) {
	l := logic.NewFollowActionLogic(ctx, s.svcCtx)
	return l.FollowAction(in)
}

func (s *RelationServer) FollowList(ctx context.Context, in *relationclient.FollowListRequest) (*relationclient.FollowListResponse, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *RelationServer) FansList(ctx context.Context, in *relationclient.FansListRequest) (*relationclient.FansListResponse, error) {
	l := logic.NewFansListLogic(ctx, s.svcCtx)
	return l.FansList(in)
}

func (s *RelationServer) GetRelationCount(ctx context.Context, in *relationclient.GetRelationCountRequest) (*relationclient.GetRelationCountResponse, error) {
	l := logic.NewGetRelationCountLogic(ctx, s.svcCtx)
	return l.GetRelationCount(in)
}
