// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"mini-titok/service/user/rpc/userclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFanUserListRequest     = userclient.GetFanUserListRequest
	GetFanUserListResponse    = userclient.GetFanUserListResponse
	GetFollowUserListRequest  = userclient.GetFollowUserListRequest
	GetFollowUserListResponse = userclient.GetFollowUserListResponse
	LoginRequest              = userclient.LoginRequest
	LoginResponse             = userclient.LoginResponse
	RegisterRequest           = userclient.RegisterRequest
	RegisterResponse          = userclient.RegisterResponse
	UserInfo                  = userclient.UserInfo
	UserInfoRequest           = userclient.UserInfoRequest
	UserInfoResponse          = userclient.UserInfoResponse

	User interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		GetFollowUserList(ctx context.Context, in *GetFollowUserListRequest, opts ...grpc.CallOption) (*GetFollowUserListResponse, error)
		GetFanUserList(ctx context.Context, in *GetFanUserListRequest, opts ...grpc.CallOption) (*GetFanUserListResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := userclient.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := userclient.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := userclient.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) GetFollowUserList(ctx context.Context, in *GetFollowUserListRequest, opts ...grpc.CallOption) (*GetFollowUserListResponse, error) {
	client := userclient.NewUserClient(m.cli.Conn())
	return client.GetFollowUserList(ctx, in, opts...)
}

func (m *defaultUser) GetFanUserList(ctx context.Context, in *GetFanUserListRequest, opts ...grpc.CallOption) (*GetFanUserListResponse, error) {
	client := userclient.NewUserClient(m.cli.Conn())
	return client.GetFanUserList(ctx, in, opts...)
}
